import type { Metadata } from "next";
import { Urbanist } from "next/font/google";
import "./globals.css";

const urbanist = Urbanist({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: {
    template: '%s | Store',
    default: 'Store'
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children, navbar,
  footer
}: Readonly<{
  children: React.ReactNode;
  footer: React.ReactNode;
  navbar: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={urbanist.className}>
        {navbar}
        {children}
        {footer}
      </body>
    </html>
  );
}
